### ISSUE TITLE
Detect 4 axes

### ISSUE THREAD

**Issue by LETARTARE** [EtlamGit/EasyGrblSetup#1]
Hello,
first of all, my congratulations on the writing of  'EasyGrblSetup'.
The quick code reading shows a clear code and well arranged.
Two remarks:
1- I wrote 'GrblQ' (4 axes : https://github.com/LETARTARE/grblQ-Mega-4axes.git) and to detect it I adapted 'void GrblCommander::parseLine(const QString &line)'
`'if (line.mid(0, 4).startsWith("Grbl") && line.contains("['$' for help]")) {'`
2- it is unfortunate that translation into another language is not planned.

![grblsetup4axes](https://user-images.githubusercontent.com/5158475/37245614-e200b49a-2492-11e8-87db-381c6c25b5ee.png)

Good night.

**Comment by EtlamGit** [comment]
Hi and thank you for your comments!

1) I will take a look into it. Is your project compiling also on an Arduino UNO? In that case I could test with real hardware. Otherwise, I have to rely on a typical welcome message. I may use that one in your screenshot.

2) Translation is planned, but as my time is very limited not very likely to be done soon.

- Qt allows text translation, but up to now the code is not prepared for that. With that preparation done, native speakers would be able to translate (e.g. French in your case, or German for me).
- All tool tip text is borrowed from original Grbl wiki. So these texts are always English.

3) At the moment I'm spending my free time in writing a cross platform GCode player. It will share some code with this project (e.g. the status pane and GrblCommander).

**Comment by LETARTARE** [comment]
Hi,
1- the 'GrblQ' project is only for 'Mega2560' (see the wiki) and the proposed image uses 'GrblQ' with a rotating axis 'A'
2- well, 
3- can you specify 'player'?
   You did a good part of a 'Gui' to drive 'Grbl', it remains the management of 'GCode' ?
If you go to my site, watch the presentation of 'Gcv'  : https://github.com/LETARTARE/GCV/wiki ,
it's an ongoing Qt project that I'll update in a while.

I just tried 'EasyGrblSetup' again : 
1- we start on a map 'Uno' we get 3 axes,
 2- we disconnect from 'Uno'
 3- we connect to 'Mega2560-GrblQ = A' -> we always display 3 axes !!

If we reverse 'Uno' et 'Mega' > we always display 4 axes !!

Good continuation.

**Comment by EtlamGit** [comment]
to 1)
I just take a deeper look into the detection code and do not understand why your welcome message is not detected properly. As I do not have a Mega board, I have to do virtual debugging. My assumption is that your welcome message is:
`GrblQ 1.1f ['$' for help]`
so just a Q more than standard welcome message. In that case
`line.startsWith("Grbl")`
should do the same than
`line.mid(0, 4).startsWith("Grbl")`

Did you use the pre-compiled release or a self compiled binary?
It might be the case that I had not uploaded the latest build.


to 3) It is just a project for myself learning how to do CNC. I tried some other simple players, but they are either not cross-platform or do not work at all.

to 4) Yes, that is a bug. I will tackle it.

**Comment by LETARTARE** [comment]
With svn24 the problem of the detection of 'GrblQ' is solved.
To compile QT projects, I use the last 'Code::Blocks', for which I wrote a plugin ['QtPregen-1.0'](lhttps://github.com/LETARTARE/QtPregen).I am preparing the QtPregen-2.3.0 'version that will work on Linux.
For the translation, I answer on the other thread.
Cordially.

**Comment by EtlamGit** [comment]
Detection problem was caused by wrong init of UART.
